baseURL = "https://reimaginedev.github.io/"
languageCode = "en-us"
title = "Reimagine Dev"
theme = "reimagine-dev-hugo-theme"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"

googleAnalytics = ""
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
    title = "Reimagine Dev 2019"
    date = "2019-06-07"
    description = "Humans first"
    images = ["/images/social-share.jpg"]
    email = "info@prxm.it"
    keywords = "event, developers, team, talks"
    copyright = "Proximo srl - VAT 02265520425"
    cfpUrl = "https://conference-hall.io/public/event/HJRThubF4uYPkb7jSUxi"
    subscriptionUrl = ""
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = ""
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#4285f4"

[params.logos]
    jumbo = "/images/logos/reimagine-dev-logo-big.png"
    header = "/images/logos/reimagine-dev-logo-big.png"
    footer = "/images/logos/proximo.png"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true